version: '3'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_ci
volumes:
  postgres:
#河南冠杰智能科技股份有限公司   郑州市管城回族区 凯利国际中心A座1218 841  60673333
